services:
  candy:
    image: docker.io/lanthora/candy
    container_name: "candy"
    network_mode: "host"
    privileged: true
    devices:
      - "/dev/net/tun:/dev/net/tun"
    restart: "always"
    volumes:
      - ./data/candy:/var/lib/candy
  dae:
    image: docker.io/daeuniverse/dae
    container_name: "dae"
    network_mode: "host"
    privileged: true
    restart: "always"
    volumes:
      - /sys:/sys
      - ./config/dae:/etc/dae
